mode: "dev"
port: 8081

log:
  level: "debug"
  filename: "./log/bluebell.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

mysql:
  host: mysql8019
  port: 3306
  user: root
  password: root1234
  db: bluebell
  max_open_conns: 100
  max_idle_conns: 20

redis:
  host: redis507
  port: 6379
  db: 0